---
kind: pipeline
name: drone

workspace:
  base: /app
  path: git/drone

steps:
  - name: build
    image: node:alpine
    commands:
      - /bin/sh bash.sh
    environment:
      hostname:
        from_secret: hostname
      username:
        from_secret: username
      abc: abctest
  - name: deploy
    image: appleboy/drone-scp
    when:
      status:
        - success
    settings:
      hostname:
        from_secret: hostname
      username:
        from_secret: username
      source: ./*

trigger:
  branch:
    - master
  event:
    - push

